NUMBER_OF_NODES = 100
NUMBER_OF_SHARDS = 4
NUMBER_OF_TRANSACTIONS = 1000
NUMBER_OF_ACCOUNTS = 150
DEFAULT_AMOUNT = 2000
NUMBER_OF_CONDITIONS = 4
NUMBER_OF_LEADER_SHARD = 1

CONDITION_HAS='__HAS__'
CONDITION_AND='____AND____'
CONFIRMED_SHARD_NAME_PREFIX='CONFIRMED_SHARD_'
TEMPORARY_SHARD_NAME_PREFIX='TEMPORARY_SHARD_'
TRANSACTION_POOL_FOR_LEADER_NAME_PREFIX='TRANSACTION_POOL_FOR_LEADER_'
ACCOUNT_INDEX_ACCOUNT_NUMBER=0
ACCOUNT_INDEX_ACCOUNT_NAME=1
ACCOUNT_INDEX_AMOUNT=2
