from multiprocessing import Value

SHARDS = [(0, True), (1, True),
            (2, False), (3, False)
          ]  # (id,is_leader)

TOTAL_NUMBER_OF_TRANSACTIONS = 4
NUMBER_OF_ACCOUNTS = 1000
DEFAULT_AMOUNT = 3000
NUMBER_OF_CONDITIONS = 18
TRANSACTION_TYPE = 'NO_LOCK'  # NO_LOCK, OUR_PROTOCOL,LOCK
ACCOUNT_LOCK_RETRY_TIME_MS = 100
WRITE_LOG_TO_FILE = False

LOCK_FILE_TO_MAKE_THREAD_SAFE = True

CONDITION_HAS = '__HAS__'
CONDITION_AND = '____AND____'
TRANSACTION_FILE_NAME = 'TRANSACTIONS.CSV'
ACCOUNT_INDEX_ACCOUNT_NUMBER = 0
ACCOUNT_INDEX_ACCOUNT_NAME = 1
ACCOUNT_INDEX_AMOUNT = 2

TRANSACTION_STATE_INITIAL = 'INITIAL'
TRANSACTION_STATE_COMMITTED = 'COMMITTED'
TRANSACTION_STATE_ABORTED = 'ABORTED'
TRANSACTION_STATE_ROLLBACKED = 'ROLLBACKED'
SNAPSHOT_ACQUIRED = 'ACQUIRED'
SNAPSHOT_RELEASED = 'RELEASED'

LOCK_LOCKED = 'LOCKED'
LOCK_RELEASED = 'RELEASED'


MESSAGE_SEPARATOR = "***"
MESSAGE_DATA_SEPARATOR = "___"

HOST = '127.0.0.1'
INITAIL_PORT = 8085
